---
- hosts: control
  become: true
  tasks:
    - name: Delete droplet for each remote host
      digital_ocean:
        command: droplet
        id: "{{item}}"
        state: deleted
      with_items:
        - 20855359 # lb01
        - 20855447 # db01
        - 20855531 # app01
        - 20855670 # app02
