---
- hosts: control
  become: true
  tasks:
    - name: Remove old dev file with old host IP info
      file: path=/home/ansible/ansible/dev state=absent

    - name: Create new empty dev file for new host IP info
      file: path=/home/ansible/ansible/dev state=touch

    - name: Create [control] group in dev file
      lineinfile: dest=/home/ansible/ansible/dev state=present regexp='^\[control\]' line='[control]'

    - name: Create control host entry
      lineinfile: dest=/home/ansible/ansible/dev state=present regexp='^control' line='control ansible_connection=local'

    - name: pip required to install dopy
      apt: name=python-pip state=present update_cache=yes cache_valid_time=43200

    - name: pip install dopy - required for DigitalOcean module
      pip: name=dopy

    - name: Ensure root@MA-CONTROL ssh key
      user: name=root generate_ssh_key=yes

    - name: Remove existing MA-CONTROL-ROOT ssh key from DigitalOcean
      digital_ocean:
        command: ssh
        name: MA-CONTROL-ROOT
        state: absent

    - name: Ensure current MA-CONTROL-ROOT ssh key is in DigitalOcean
      vars:
        contents: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
      digital_ocean:
        command: ssh
        name: MA-CONTROL-ROOT
        state: present
        ssh_pub_key: "{{contents}}"
      register: MA_CONTROL_ROOT_KEY

    ### create hosts per Mastering Ansible configuration
    - name: Create droplet for each remote host
      digital_ocean:
        command: droplet
        name: "{{item}}"
        state: present
        image_id: ubuntu-16-04-x64
        region_id: nyc1
        size_id: 512mb
        unique_name: yes
        ssh_key_ids: "{{MA_CONTROL_ROOT_KEY.ssh_key.id}}"
      register: droplets
      with_items:
        - lb01
        - db01
        - app01
        - app02

    ### use registered droplet variables to populate dev file
    ### better way might be dynamic inventory features
    - name: Create [loadbalancer] group in dev file
      lineinfile: dest=/home/ansible/ansible/dev state=present regexp='^\[loadbalancer\]' line='[loadbalancer]'

    - name: Create lb01 host entry
      lineinfile:
        dest: /home/ansible/ansible/dev
        state: present
        regexp: '^lb01'
        line: 'lb01 ansible_host={{droplets.results[0].droplet.networks.v4[0].ip_address}}'

    - name: Create [database] group in dev file
      lineinfile: dest=/home/ansible/ansible/dev state=present regexp='^\[database\]' line='[database]'

    - name: Create db01 host entry
      lineinfile:
        dest: /home/ansible/ansible/dev
        state: present
        regexp: '^db01'
        line: 'db01 ansible_host={{droplets.results[1].droplet.networks.v4[0].ip_address}}'

    - name: Create [webserver] group in dev file
      lineinfile: dest=/home/ansible/ansible/dev state=present regexp='^\[webserver\]' line='[webserver]'

    - name: Create app01 host entry
      lineinfile:
        dest: /home/ansible/ansible/dev
        state: present
        regexp: '^app01'
        line: 'app01 ansible_host={{droplets.results[2].droplet.networks.v4[0].ip_address}}'

    - name: Create app02 host entry
      lineinfile:
        dest: /home/ansible/ansible/dev
        state: present
        regexp: '^app02'
        line: 'app02 ansible_host={{droplets.results[3].droplet.networks.v4[0].ip_address}}'


# after all that you should be able to ssh root@fleet_host_ip from ansible@MA-CONTROL
