---
- hosts: all
  remote_user: root # have to run as root to establish passwordless sudo for ansible user
  become: yes # needed for sudo access to control machine via local connection
  tasks:
    - name: Update apt packages
      apt: update_cache=yes cache_valid_time=43200
    - name: Upgrade packages
      apt: upgrade=dist
    - name: Configure ansible user
      user: name=ansible append=yes groups=sudo generate_ssh_key=yes
    - name: Set up ssh to remote ansible users
      authorized_key: user=ansible key="{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
    - name: Allow passwordless sudo for ansible user
      lineinfile: "dest=/etc/sudoers state=present regexp='^ansible' line='ansible ALL=(ALL) NOPASSWD: ALL'"
    - name: Add ufw rule allow OpenSSH
      ufw: rule=allow name=OpenSSH
    - name: Enable ufw
      ufw: state=enabled
    - name: Install python3 tools
      apt: name={{item}} state=present
      with_items:
        - python3-dev
        - python3-pip
        - python3.4-venv
    - name: Restart servers
      command: /sbin/shutdown -r +1
