---
- hosts: database
  remote_user: root
  tasks:
    - name: Update apt
      apt: update_cache=yes
    - name: Install postgresql and postgresql-contrib
      apt: name={{item}} state=present
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
