---
- hosts: loadbalancer
  remote_user: root
  tasks:
    - name: update apt
      apt: update_cache=yes
    - name: install nginx
      apt: name=nginx state=present
    - name: Add Nginx HTTP to ufw rules
      ufw: rule=allow name='Nginx HTTP'
    - name: Reload ufw
      ufw: state=reloaded
